# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1.4

# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install build dependencies
RUN apk add --no-cache git

# Copy manifests
COPY package.json yarn.lock tsconfig.json tsup.config.ts ./
# Copy source
COPY src ./src

# Install dependencies and build
RUN yarn install --frozen-lockfile && yarn build

# Production stage
FROM node:lts-alpine AS runner
WORKDIR /app

# Copy built artifacts and necessary files
COPY --from=builder /app/lib ./lib
COPY package.json yarn.lock ./

# Install production dependencies
RUN yarn install --production --frozen-lockfile

# Launch the MCP server via STDIO
ENTRYPOINT ["node", "lib/index.js"]
